# docker-compose.yml
# ----------------------------------------------------------------------------
# Composes Docker containers and volumes to a runnable MySQL database
# ----------------------------------------------------------------------------
#
---
version: '3'

services:

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: jeedemo
      MYSQL_PASSWORD: fwpss2018
      MYSQL_DATABASE: jeedemo_db
   
volumes:

  mysql-data:





  